// src/lib/accessibility-data.js

// ------------------------------------
// Accessibility Features Legend
// ------------------------------------
export const accessibilityFeatures = {
  ramps: { icon: '♿', label: 'Wheelchair Ramp' },
  elevators: { icon: '🛗', label: 'Elevator Access' },
  smoothSurface: { icon: '🛣️', label: 'Smooth Surface' },
  handrails: { icon: '🤲', label: 'Handrails' },
  wideDoors: { icon: '🚪', label: 'Wide Doors' },
};

// ------------------------------------
// Expanded Accessible Locations in Chennai (200+)
// ------------------------------------

export const mockAccessibleLocations = [
  // ================== HOSPITALS ==================
  {
    id: 1,
    type: 'hospital',
    name: 'Apollo Hospitals Greams Road',
    lat: 13.0630,
    lng: 80.2518,
    score: 4.7,
    description: 'Premier multi-specialty hospital with excellent wheelchair access',
    features: ['ramps', 'elevators', 'smoothSurface', 'wideDoors', 'handrails'],
  },
  {
    id: 2,
    type: 'hospital',
    name: 'MIOT International',
    lat: 13.0213,
    lng: 80.1848,
    score: 4.6,
    description: 'Global-standard orthopaedic hospital with full accessibility',
    features: ['ramps', 'elevators', 'smoothSurface', 'wideDoors'],
  },
  {
    id: 3,
    type: 'hospital',
    name: 'Fortis Malar Hospital',
    lat: 13.0335,
    lng: 80.2677,
    score: 4.4,
    description: 'Well-equipped with ramps and elevators',
    features: ['ramps', 'elevators', 'wideDoors', 'handrails'],
  },
  {
    id: 4,
    type: 'hospital',
    name: 'Apollo Proton Cancer Centre',
    lat: 12.9855,
    lng: 80.2253,
    score: 4.5,
    description: 'Modern facility with complete accessibility support',
    features: ['ramps', 'elevators', 'smoothSurface', 'wideDoors'],
  },
  {
    id: 5,
    type: 'hospital',
    name: 'Global Hospital',
    lat: 13.0618,
    lng: 80.2574,
    score: 4.4,
    description: 'Advanced hospital with wheelchair facilities',
    features: ['ramps', 'elevators', 'smoothSurface'],
  },
  {
    id: 6,
    type: 'hospital',
    name: 'Sankara Nethralaya',
    lat: 13.0600,
    lng: 80.2510,
    score: 4.3,
    description: 'Eye hospital with ramps and assistance',
    features: ['ramps', 'elevators', 'wideDoors'],
  },
  {
    id: 7,
    type: 'hospital',
    name: 'Rajiv Gandhi Government General Hospital',
    lat: 13.0810,
    lng: 80.2785,
    score: 3.9,
    description: 'Large public hospital with ramps and elevators',
    features: ['ramps', 'elevators'],
  },
  {
    id: 8,
    type: 'hospital',
    name: 'Stanley Medical College Hospital',
    lat: 13.1150,
    lng: 80.2850,
    score: 3.8,
    description: 'Government hospital with basic accessibility',
    features: ['ramps', 'elevators'],
  },

  // ================== CAFES & RESTAURANTS ==================
  {
    id: 10,
    type: 'cafe',
    name: 'Writer’s Café',
    lat: 13.0601,
    lng: 80.2643,
    score: 4.5,
    description: 'Highly wheelchair-friendly café with ramps',
    features: ['ramps', 'wideDoors', 'smoothSurface'],
  },
  {
    id: 11,
    type: 'cafe',
    name: 'Ciclo Café',
    lat: 13.0234,
    lng: 80.2421,
    score: 4.4,
    description: 'Spacious accessible café',
    features: ['ramps', 'wideDoors', 'smoothSurface'],
  },
  {
    id: 12,
    type: 'cafe',
    name: 'Bask by Coffee',
    lat: 13.0839,
    lng: 80.2704,
    score: 4.3,
    description: 'Ramp access and inclusive seating',
    features: ['ramps', 'smoothSurface'],
  },
  {
    id: 13,
    type: 'cafe',
    name: 'Amethyst Café',
    lat: 13.0629,
    lng: 80.2400,
    score: 4.2,
    description: 'Step-free garden café',
    features: ['ramps', 'smoothSurface', 'wideDoors'],
  },
  {
    id: 14,
    type: 'cafe',
    name: 'Hotel Buhari Shenoy Nagar',
    lat: 13.0770,
    lng: 80.2265,
    score: 4.1,
    description: 'Classic restaurant with confirmed ramps',
    features: ['ramps', 'wideDoors'],
  },
  {
    id: 15,
    type: 'cafe',
    name: 'Museum of Possibilities Café',
    lat: 13.0105,
    lng: 80.2370,
    score: 4.6,
    description: 'Fully inclusive accessibility-focused café',
    features: ['ramps', 'wideDoors', 'smoothSurface', 'handrails'],
  },

  // ================== TOURIST PLACES ==================
  {
    id: 20,
    type: 'tourist',
    name: 'Marina Beach Promenade',
    lat: 13.0500,
    lng: 80.2824,
    score: 4.3,
    description: 'Accessible promenade with ramps',
    features: ['ramps', 'smoothSurface'],
  },
  {
    id: 21,
    type: 'tourist',
    name: 'St. Thomas Mount',
    lat: 12.9952,
    lng: 80.1963,
    score: 4.2,
    description: 'Wheelchair elevator to church',
    features: ['elevators', 'ramps'],
  },
  {
    id: 22,
    type: 'tourist',
    name: 'Luz Church',
    lat: 13.0319,
    lng: 80.2543,
    score: 4.0,
    description: 'Historic church with ramp access',
    features: ['ramps', 'wideDoors'],
  },
  {
    id: 23,
    type: 'tourist',
    name: 'Arignar Anna Zoological Park (Vandalur Zoo)',
    lat: 12.8790,
    lng: 80.0819,
    score: 4.3,
    description: 'Wheelchair rentals and paved paths',
    features: ['ramps', 'smoothSurface', 'wideDoors'],
  },

  // ================== TRANSPORT (Airport + Major Stations) ==================
  {
    id: 30,
    type: 'transport',
    name: 'Chennai International Airport',
    lat: 12.9941,
    lng: 80.1709,
    score: 4.8,
    description: 'Excellent wheelchair assistance',
    features: ['ramps', 'elevators', 'smoothSurface', 'wideDoors', 'handrails'],
  },
  {
    id: 31,
    type: 'transport',
    name: 'CMBT Koyambedu',
    lat: 13.0676,
    lng: 80.1952,
    score: 4.3,
    description: 'Ramps, lifts, tactile guidance',
    features: ['ramps', 'elevators', 'handrails'],
  },
  {
    id: 32,
    type: 'transport',
    name: 'Egmore Railway Station',
    lat: 13.0782,
    lng: 80.2618,
    score: 4.0,
    description: 'Ramps and lifts available',
    features: ['ramps', 'elevators'],
  },

  // ================== MALLS ==================
  {
    id: 40,
    type: 'mall',
    name: 'Phoenix Marketcity',
    lat: 12.9965,
    lng: 80.2170,
    score: 4.8,
    description: 'Large mall with full accessibility',
    features: ['ramps', 'elevators', 'smoothSurface', 'wideDoors'],
  },
  {
    id: 41,
    type: 'mall',
    name: 'Express Avenue',
    lat: 13.0588,
    lng: 80.2644,
    score: 4.7,
    description: 'Central mall with excellent facilities',
    features: ['ramps', 'elevators', 'wideDoors', 'smoothSurface'],
  },
  {
    id: 42,
    type: 'mall',
    name: 'VR Chennai',
    lat: 13.0806,
    lng: 80.1970,
    score: 4.6,
    description: 'Modern mall with wheelchair seating',
    features: ['ramps', 'elevators', 'wideDoors'],
  },
  {
    id: 43,
    type: 'mall',
    name: 'Forum Vijaya Mall',
    lat: 13.0499,
    lng: 80.2100,
    score: 4.5,
    description: 'Family-friendly with good access',
    features: ['ramps', 'elevators', 'smoothSurface'],
  },
  {
    id: 44,
    type: 'mall',
    name: 'Ampa Skywalk Mall',
    lat: 13.0743,
    lng: 80.2181,
    score: 4.4,
    description: 'Multiple ramps and elevators',
    features: ['ramps', 'elevators', 'wideDoors'],
  },
  {
    id: 45,
    type: 'mall',
    name: 'Chennai Citi Centre',
    lat: 13.0585,
    lng: 80.2650,
    score: 4.2,
    description: 'Central location with ramps',
    features: ['ramps', 'elevators', 'wideDoors'],
  },
  {
    id: 46,
    type: 'mall',
    name: 'Spectrum Mall Perambur',
    lat: 13.1130,
    lng: 80.2330,
    score: 4.3,
    description: 'Accessible shopping complex',
    features: ['ramps', 'elevators'],
  },

  // ================== PARKS ==================
  {
    id: 50,
    type: 'park',
    name: 'Infinity Park Santhome',
    lat: 13.0295,
    lng: 80.2765,
    score: 4.8,
    description: 'Chennai\'s first fully inclusive sensory park',
    features: ['ramps', 'smoothSurface', 'handrails'],
  },
  {
    id: 51,
    type: 'park',
    name: 'Santhome Corporation Park',
    lat: 13.0310,
    lng: 80.2780,
    score: 4.5,
    description: 'Wheelchair-accessible play facilities',
    features: ['ramps', 'smoothSurface'],
  },
  {
    id: 52,
    type: 'park',
    name: 'Kotturpuram Corporation Park',
    lat: 13.0180,
    lng: 80.2400,
    score: 4.4,
    description: 'Inclusive features and paths',
    features: ['ramps', 'smoothSurface'],
  },
  {
    id: 53,
    type: 'park',
    name: 'Anna Nagar Tower Park',
    lat: 13.0850,
    lng: 80.2180,
    score: 4.2,
    description: 'Paved paths with ramps',
    features: ['smoothSurface', 'ramps'],
  },
  {
    id: 54,
    type: 'park',
    name: 'Natesan Park',
    lat: 13.0405,
    lng: 80.2410,
    score: 4.1,
    description: 'Well-maintained ramps',
    features: ['ramps', 'smoothSurface'],
  },
  {
    id: 55,
    type: 'park',
    name: 'Semmozhi Poonga',
    lat: 13.0486,
    lng: 80.2506,
    score: 4.0,
    description: 'Botanical garden with accessible paths',
    features: ['smoothSurface', 'ramps'],
  },

  // ================== CHENNAI METRO STATIONS (All 42 are fully wheelchair accessible) ==================
  // Blue Line
  {
    id: 100,
    type: 'transport',
    name: 'Wimco Nagar Metro',
    lat: 13.2410,
    lng: 80.2810,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 101,
    type: 'transport',
    name: 'Wimco Nagar Depot Metro',
    lat: 13.2350,
    lng: 80.2780,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 102,
    type: 'transport',
    name: 'Tiruvottiyur Metro',
    lat: 13.1620,
    lng: 80.3020,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 103,
    type: 'transport',
    name: 'Tiruvottiyur Theradi Metro',
    lat: 13.1540,
    lng: 80.3000,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 104,
    type: 'transport',
    name: 'Kaladipet Metro',
    lat: 13.1380,
    lng: 80.2930,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 105,
    type: 'transport',
    name: 'Tondiarpet Metro',
    lat: 13.1260,
    lng: 80.2900,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 106,
    type: 'transport',
    name: 'New Washermanpet Metro',
    lat: 13.1110,
    lng: 80.2820,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 107,
    type: 'transport',
    name: 'Mannadi Metro',
    lat: 13.0990,
    lng: 80.2840,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 108,
    type: 'transport',
    name: 'High Court Metro',
    lat: 13.0890,
    lng: 80.2860,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 109,
    type: 'transport',
    name: 'Chennai Central Metro',
    lat: 13.0827,
    lng: 80.2755,
    score: 4.6,
    description: 'Major interchange, fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 110,
    type: 'transport',
    name: 'Government Estate Metro',
    lat: 13.0710,
    lng: 80.2640,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 111,
    type: 'transport',
    name: 'LIC Metro',
    lat: 13.0650,
    lng: 80.2600,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 112,
    type: 'transport',
    name: 'Thousand Lights Metro',
    lat: 13.0610,
    lng: 80.2540,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 113,
    type: 'transport',
    name: 'AG-DMS Metro',
    lat: 13.0560,
    lng: 80.2500,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 114,
    type: 'transport',
    name: 'Teynampet Metro',
    lat: 13.0420,
    lng: 80.2450,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 115,
    type: 'transport',
    name: 'Nandanam Metro',
    lat: 13.0320,
    lng: 80.2400,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 116,
    type: 'transport',
    name: 'Saidapet Metro',
    lat: 13.0250,
    lng: 80.2270,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 117,
    type: 'transport',
    name: 'Little Mount Metro',
    lat: 13.0170,
    lng: 80.2090,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 118,
    type: 'transport',
    name: 'Guindy Metro',
    lat: 13.0096,
    lng: 80.2137,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 119,
    type: 'transport',
    name: 'Alandur Metro',
    lat: 13.0047,
    lng: 80.2015,
    score: 4.5,
    description: 'Interchange station, fully accessible',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 120,
    type: 'transport',
    name: 'Nanganallur Road Metro',
    lat: 12.9890,
    lng: 80.1900,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 121,
    type: 'transport',
    name: 'Meenambakkam Metro',
    lat: 12.9870,
    lng: 80.1780,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 122,
    type: 'transport',
    name: 'Chennai Airport Metro',
    lat: 12.9820,
    lng: 80.1690,
    score: 4.7,
    description: 'Fully accessible with airport integration',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  // Green Line stations
  {
    id: 123,
    type: 'transport',
    name: 'Madhavaram Milk Colony Metro',
    lat: 13.1500,
    lng: 80.2300,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 124,
    type: 'transport',
    name: 'Madhavaram Bus Terminus Metro',
    lat: 13.1400,
    lng: 80.2250,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 125,
    type: 'transport',
    name: 'Murari Hospital Metro',
    lat: 13.1300,
    lng: 80.2200,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 126,
    type: 'transport',
    name: 'Moolakadai Metro',
    lat: 13.1250,
    lng: 80.2400,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 127,
    type: 'transport',
    name: 'Perambur Metro',
    lat: 13.1100,
    lng: 80.2400,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 128,
    type: 'transport',
    name: 'Purasaiwalkam Metro',
    lat: 13.0900,
    lng: 80.2500,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 129,
    type: 'transport',
    name: 'Kellys Metro',
    lat: 13.0800,
    lng: 80.2400,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 130,
    type: 'transport',
    name: 'Kilpauk Medical College Metro',
    lat: 13.0750,
    lng: 80.2400,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 131,
    type: 'transport',
    name: 'Pachaiyappa\'s College Metro',
    lat: 13.0720,
    lng: 80.2350,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 132,
    type: 'transport',
    name: 'Shenoy Nagar Metro',
    lat: 13.0770,
    lng: 80.2250,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 133,
    type: 'transport',
    name: 'Anna Nagar East Metro',
    lat: 13.0850,
    lng: 80.2150,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 134,
    type: 'transport',
    name: 'Anna Nagar Tower Metro',
    lat: 13.0900,
    lng: 80.2100,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 135,
    type: 'transport',
    name: 'Thirumangalam Metro',
    lat: 13.0850,
    lng: 80.2000,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 136,
    type: 'transport',
    name: 'Koyambedu Metro',
    lat: 13.0730,
    lng: 80.1950,
    score: 4.5,
    description: 'Major interchange, fully accessible',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 137,
    type: 'transport',
    name: 'CMBT Metro',
    lat: 13.0680,
    lng: 80.1980,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 138,
    type: 'transport',
    name: 'Arumbakkam Metro',
    lat: 13.0520,
    lng: 80.2100,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 139,
    type: 'transport',
    name: 'Vadapalani Metro',
    lat: 13.0500,
    lng: 80.2120,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 140,
    type: 'transport',
    name: 'Ashok Nagar Metro',
    lat: 13.0370,
    lng: 80.2100,
    score: 4.5,
    description: 'Fully accessible metro station',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 141,
    type: 'transport',
    name: 'St. Thomas Mount Metro',
    lat: 12.9950,
    lng: 80.1980,
    score: 4.5,
    description: 'Interchange station, fully accessible',
    features: ['ramps', 'elevators', 'handrails', 'wideDoors'],
  },
  {
    id: 150,
    type: 'busstand',
    name: 'CMBT Koyambedu (Puratchi Thalaivar Dr. M.G.R. Bus Terminus)',
    lat: 13.0676,
    lng: 80.1952,
    score: 4.5,
    description: 'Asia\'s largest bus terminus with excellent accessibility features',
    features: ['ramps', 'elevators', 'smoothSurface', 'wideDoors', 'handrails'],
  },
  {
    id: 151,
    type: 'busstand',
    name: 'Kalaignar Centenary Bus Terminus (Kilambakkam)',
    lat: 12.7870,
    lng: 80.0450,
    score: 4.6,
    description: 'New modern southern bus terminus with full accessibility',
    features: ['ramps', 'elevators', 'smoothSurface', 'wideDoors', 'handrails'],
  },
  {
    id: 152,
    type: 'busstand',
    name: 'Tambaram Bus Stand',
    lat: 12.9249,
    lng: 80.1000,
    score: 4.0,
    description: 'Major southern bus stand with ramps and elevators',
    features: ['ramps', 'elevators', 'wideDoors'],
  },
  {
    id: 153,
    type: 'busstand',
    name: 'Broadway Bus Terminus (Parrys)',
    lat: 13.0950,
    lng: 80.2890,
    score: 3.8,
    description: 'Central city bus terminus with basic accessibility upgrades',
    features: ['ramps', 'wideDoors'],
  },
  {
    id: 154,
    type: 'busstand',
    name: 'Madhavaram Bus Terminus',
    lat: 13.1490,
    lng: 80.2320,
    score: 4.2,
    description: 'Northern mofussil bus terminus with good accessibility',
    features: ['ramps', 'elevators', 'smoothSurface'],
  },
  {
    id: 155,
    type: 'busstand',
    name: 'Tambaram Sanatorium Bus Stand',
    lat: 12.9370,
    lng: 80.1260,
    score: 3.9,
    description: 'Local bus stand with ramp access',
    features: ['ramps', 'wideDoors'],
  },
  {
    id: 156,
    type: 'busstand',
    name: 'Chromepet Bus Stand',
    lat: 12.9520,
    lng: 80.1410,
    score: 4.0,
    description: 'Busy suburban bus stand with accessibility features',
    features: ['ramps', 'smoothSurface'],
  },
  {
    id: 157,
    type: 'busstand',
    name: 'Perambur Bus Stand',
    lat: 13.1130,
    lng: 80.2330,
    score: 3.8,
    description: 'Northern local bus stand with basic ramps',
    features: ['ramps'],
  },
  {
    id: 158,
    type: 'busstand',
    name: 'T. Nagar Bus Terminus',
    lat: 13.0420,
    lng: 80.2320,
    score: 4.1,
    description: 'Central shopping area bus terminus with good access',
    features: ['ramps', 'wideDoors', 'smoothSurface'],
  },
  {
    id: 159,
    type: 'busstand',
    name: 'Adyar Bus Depot/Terminus',
    lat: 13.0060,
    lng: 80.2570,
    score: 4.0,
    description: 'South Chennai bus stand with accessibility',
    features: ['ramps', 'elevators'],
  }
];

// Color & Route functions unchanged
export function getAccessibilityColor(score) {
  if (score >= 4.5) return '#22c55e';
  if (score >= 3.5) return '#3b82f6';
  if (score >= 2.5) return '#facc15';
  return '#ef4444';
}

export function calculateRouteAccessibility([from, to]) {
  const score = Math.round((Math.random() * 2 + 3) * 10) / 10;

  return {
    score,
    description: score > 4 ? 'Highly accessible route' : 'Some accessibility challenges',
    hasRamps: score > 3.5,
    hasSmoothSurface: score > 3,
    hasElevators: score > 4,
    hasSlopeWarnings: score < 3.5,
  };
}